<?php
	
class app_install_forum {
	
	/**
	** This file has been automatically generated
	** TS: 1417560588 (2nd of December 2014 11:49:48 PM)
	** 
	** Do not edit. Use CP Build Tools
	*/
	
	public function info()
	{
		return array(
			'unique_id'	=> 'net.cipherpixel.forum',
			'name' 		=> 'forum',
			'sexyname' 	=> 'CP-Forum',
			'desc' 		=> '',
			'ver'  		=> '1.0.0.b',
		);
	}
	
	public function structure_queries()
	{
		
		return '{"attachment":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"time":{"Field":"time","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"upload_by":{"Field":"upload_by","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"name":{"Field":"name","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"path":{"Field":"path","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}},"forums":{"id":{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"name":{"Field":"name","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"slug":{"Field":"slug","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"desc":{"Field":"desc","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"parent":{"Field":"parent","Type":"int(225)","Null":"NO","Key":"","Default":"0","Extra":""},"allowThreads":{"Field":"allowThreads","Type":"int(1)","Null":"NO","Key":"","Default":"1","Extra":""},"order":{"Field":"order","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"lastPostTime":{"Field":"lastPostTime","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"lastPostUser":{"Field":"lastPostUser","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"lastPostThread":{"Field":"lastPostThread","Type":"int(225)","Null":"NO","Key":"","Default":"0","Extra":""},"postCount":{"Field":"postCount","Type":"int(225)","Null":"NO","Key":"","Default":"0","Extra":""},"threadCount":{"Field":"threadCount","Type":"int(225)","Null":"NO","Key":"","Default":"0","Extra":""},"hiddenThreadCount":{"Field":"hiddenThreadCount","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"isLink":{"Field":"isLink","Type":"int(1)","Null":"NO","Key":"","Default":"0","Extra":""},"newTab":{"Field":"newTab","Type":"int(1)","Null":"NO","Key":"","Default":"1","Extra":""},"linkUrl":{"Field":"linkUrl","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"threadSortOrder":{"Field":"threadSortOrder","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"threadSortField":{"Field":"threadSortField","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"show_rules":{"Field":"show_rules","Type":"int(1)","Null":"NO","Key":"","Default":"0","Extra":""},"rules":{"Field":"rules","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}},"groups":{"canViewBoard":{"Field":"canViewBoard","Type":"int(1)","Null":"NO","Key":"","Default":"1","Extra":""},"canViewBoardOffline":{"Field":"canViewBoardOffline","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"globalMod":{"Field":"globalMod","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"canLock":{"Field":"canLock","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"canLockOwn":{"Field":"canLockOwn","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"canPostInLock":{"Field":"canPostInLock","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"canPin":{"Field":"canPin","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"canHide":{"Field":"canHide","Type":"int(1)","Null":"NO","Key":"","Default":"0","Extra":""},"canDelete":{"Field":"canDelete","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"canDeleteOwn":{"Field":"canDeleteOwn","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"canDeletePosts":{"Field":"canDeletePosts","Type":"int(1)","Null":"NO","Key":"","Default":"0","Extra":""},"canDeleteOwnPosts":{"Field":"canDeleteOwnPosts","Type":"int(1)","Null":"NO","Key":"","Default":"0","Extra":""},"canEditPosts":{"Field":"canEditPosts","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"canEditOwnPosts":{"Field":"canEditOwnPosts","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"canRep":{"Field":"canRep","Type":"int(1)","Null":"NO","Key":"","Default":"1","Extra":""},"canMove":{"Field":"canMove","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"canRename":{"Field":"canRename","Type":"int(1)","Null":"NO","Key":"","Default":"0","Extra":""},"canViewAs":{"Field":"canViewAs","Type":"int(1)","Null":"YES","Key":"","Default":null,"Extra":""},"canBeViewedAs":{"Field":"canBeViewedAs","Type":"int(1)","Null":"YES","Key":"","Default":"1","Extra":""}},"posts":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"threadId":{"Field":"threadId","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"posterId":{"Field":"posterId","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"visible":{"Field":"visible","Type":"int(1)","Null":"NO","Key":"","Default":"1","Extra":""},"postContent":{"Field":"postContent","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"postTime":{"Field":"postTime","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"likes":{"Field":"likes","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"history":{"Field":"history","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"attachments":{"Field":"attachments","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"deletedBy":{"Field":"deletedBy","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""}},"threads":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"title":{"Field":"title","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"slug":{"Field":"slug","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"visible":{"Field":"visible","Type":"int(1)","Null":"NO","Key":"","Default":"1","Extra":""},"forumId":{"Field":"forumId","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"firstPost":{"Field":"firstPost","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"isLocked":{"Field":"isLocked","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"isPinned":{"Field":"isPinned","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"starterId":{"Field":"starterId","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"startTime":{"Field":"startTime","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"lastPostTime":{"Field":"lastPostTime","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"lastPost":{"Field":"lastPost","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"lastPostUser":{"Field":"lastPostUser","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"postCount":{"Field":"postCount","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"hiddenCount":{"Field":"hiddenCount","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"views":{"Field":"views","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"notiArray":{"Field":"notiArray","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}},"users":{"postCount":{"Field":"postCount","Type":"int(20)","Null":"NO","Key":"","Default":null,"Extra":""},"threadCount":{"Field":"threadCount","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""}}}';

		
	}
	
	public function init_queries()
	{
		
		return array(
			'globalcats' => array(
				'0' => array(
					'text_id' => 'blogs',
					'order' => '2',
					'enabled' => '1',
					'modId' => 'net.cipherpixel.forum',
					'subcat' => 'forum',
					'name' => 'Blogs',
					'desc' => 'Manage user blogs',
					'icon' => 'images/globalicons/pencil.png',
				),
				'1' => array(
					'text_id' => 'f_t_ps',
					'order' => '1',
					'enabled' => '1',
					'modId' => 'net.cipherpixel.forum',
					'subcat' => 'forum',
					'name' => 'Forums, Threads and Posts',
					'desc' => 'Change how content is displayed and created',
					'icon' => 'images/globalicons/forums.png',
				),
				'2' => array(
					'text_id' => 'google_api',
					'order' => '2',
					'enabled' => '1',
					'modId' => 'net.cipherpixel.forum',
					'subcat' => 'busers',
					'name' => 'Google API',
					'desc' => 'Manage Google Login and API Options',
					'icon' => 'images/globalicons/google.png',
				),
			),
	
			'globals' => array(
				'0' => array(
					'catId' => 'f_t_ps',
					'tab' => '',
					'subcat' => '',
					'modId' => 'net.cipherpixel.forum',
					'arrayTitle' => 'boardOnline',
					'title' => 'Is the board online?',
					'desc' => 'Use this function to turn the board offline for maintenance or another reason',
					'value' => '1',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'1' => array(
					'catId' => 'f_t_ps',
					'tab' => '',
					'subcat' => '',
					'modId' => 'net.cipherpixel.forum',
					'arrayTitle' => 'offlineMsg',
					'title' => 'Offline Message',
					'desc' => 'Text to show visitors if the board is set offline (above) - leave blank to show a default message',
					'value' => 'Please try again later as the board is currently offline',
					'valueType' => 'area',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'2' => array(
					'catId' => 'f_t_ps',
					'tab' => '',
					'subcat' => '',
					'modId' => 'net.cipherpixel.forum',
					'arrayTitle' => 'lockedText',
					'title' => 'Locked text',
					'desc' => 'Prefix to thread name if the thread is locked',
					'value' => 'Locked',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'3' => array(
					'catId' => 'f_t_ps',
					'tab' => '',
					'subcat' => '',
					'modId' => 'net.cipherpixel.forum',
					'arrayTitle' => 'pinnedText',
					'title' => 'Pinned Text',
					'desc' => 'Prefix to thread name is the thread is pinned',
					'value' => 'Pinned',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'4' => array(
					'catId' => 'f_t_ps',
					'tab' => '',
					'subcat' => '',
					'modId' => 'net.cipherpixel.forum',
					'arrayTitle' => 'postsPerPage',
					'title' => 'Posts per Page',
					'desc' => 'How many posts to display per page',
					'value' => '10',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'5' => array(
					'catId' => 'f_t_ps',
					'tab' => '',
					'subcat' => '',
					'modId' => 'net.cipherpixel.forum',
					'arrayTitle' => 'forum_requires_display_name',
					'title' => 'Require Display Name',
					'desc' => 'When logged in from a social network (ie Google) are users still required to set a custom display name?',
					'value' => '1',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'6' => array(
					'catId' => 'blogs',
					'tab' => '',
					'subcat' => '',
					'modId' => 'net.cipherpixel.forum',
					'arrayTitle' => 'enableBlogs',
					'title' => 'Enable Blogs',
					'desc' => 'Decide whether to turn the blog system on or off',
					'value' => '1',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'7' => array(
					'catId' => 'blogs',
					'tab' => '',
					'subcat' => '',
					'modId' => 'net.cipherpixel.forum',
					'arrayTitle' => 'blogMenuText',
					'title' => 'Menubar Text',
					'desc' => 'Text to show on the menubar',
					'value' => 'Blog',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'8' => array(
					'catId' => 'blogs',
					'tab' => '',
					'subcat' => '',
					'modId' => 'net.cipherpixel.forum',
					'arrayTitle' => 'commentsOn',
					'title' => 'Turn Comments On',
					'desc' => 'Toggle blog comments on or off',
					'value' => '1',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'9' => array(
					'catId' => 'blogs',
					'tab' => '',
					'subcat' => '',
					'modId' => 'net.cipherpixel.forum',
					'arrayTitle' => 'blogComPerPage',
					'title' => 'Comments per page',
					'desc' => 'Enter how many blog comments to display per page',
					'value' => '10',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'10' => array(
					'catId' => 'f_t_ps',
					'tab' => '',
					'subcat' => '',
					'modId' => 'net.cipherpixel.forum',
					'arrayTitle' => 'newsForum',
					'title' => 'News Forum',
					'desc' => 'Enter the news forum. Leave blank to turn off.',
					'value' => '2',
					'valueType' => 'drop',
					'valueFunction' => 'getBoard',
					'valueOptions' => '',
					'valueDef' => '2',
				),
				'11' => array(
					'catId' => 'f_t_ps',
					'tab' => '',
					'subcat' => '',
					'modId' => 'net.cipherpixel.forum',
					'arrayTitle' => 'threadsPerPage',
					'title' => 'Threads per page',
					'desc' => 'How many threads to display in each page of a forum?',
					'value' => '15',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'12' => array(
					'catId' => 'f_t_ps',
					'tab' => '',
					'subcat' => '',
					'modId' => 'net.cipherpixel.forum',
					'arrayTitle' => 'threadTitlePreviewLen',
					'title' => 'Thread Title Preview Length',
					'desc' => 'Set the amount of characters a thread title has before being trimmed ',
					'value' => '35',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
			),
	
			'groupsettings' => array(
				'0' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => '',
					'subcat' => 'access',
					'enabled' => '1',
					'name' => 'canViewBoard',
					'title' => 'Can View Board',
					'desc' => 'Set whether members of this group can view the board',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '1',
				),
				'1' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => '',
					'subcat' => 'access',
					'enabled' => '1',
					'name' => 'canViewBoardOffline',
					'title' => 'Can View Board Offline',
					'desc' => 'Set whether members of this group can view the board when it has been set as offline',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'2' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => '',
					'subcat' => '',
					'enabled' => '1',
					'name' => 'canViewMembers',
					'title' => 'Can view members',
					'desc' => 'Set whether members of this group can view other users profiles',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '1',
				),
				'3' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'modopts',
					'subcat' => 'global',
					'enabled' => '1',
					'name' => 'globalMod',
					'title' => 'Global Moderator',
					'desc' => 'Set whether users of this group can user their moderator powers (set below) on all forums',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'4' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'modopts',
					'subcat' => 'mod',
					'enabled' => '1',
					'name' => 'canLock',
					'title' => 'Can Lock Threads',
					'desc' => 'Set whether members of this group can lock threads in forums they moderate',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'5' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'ownopts',
					'subcat' => 'own',
					'enabled' => '1',
					'name' => 'canLockOwn',
					'title' => 'Can Lock Own Threads',
					'desc' => 'Set whether members of this group can lock their own threads',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'6' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'modopts',
					'subcat' => 'mod',
					'enabled' => '1',
					'name' => 'canPostInLock',
					'title' => 'Can Post In Locked Threads',
					'desc' => 'Set whether members of this group can post in locked threads of forums they moderate',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'7' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'modopts',
					'subcat' => 'mod',
					'enabled' => '1',
					'name' => 'canPin',
					'title' => 'Can Pin Threads',
					'desc' => 'Set whether members of this group can pin threads in forums they moderate',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'8' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'modopts',
					'subcat' => 'mod',
					'enabled' => '1',
					'name' => 'canHide',
					'title' => 'Can Approve, Hide and Unapprove threads',
					'desc' => 'Set whether members of this group can approve, hide and unapprove threads in forums they moderate',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'9' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'modopts',
					'subcat' => 'mod',
					'enabled' => '1',
					'name' => 'canDelete',
					'title' => 'Can Delete Threads',
					'desc' => 'Set whether members of this group can delete threads in forums they moderate',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'10' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'ownopts',
					'subcat' => 'own',
					'enabled' => '1',
					'name' => 'canDeleteOwn',
					'title' => 'Can Delete Own Threads',
					'desc' => 'Set whether members of this group can delete their own threads',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'11' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'modopts',
					'subcat' => 'mod',
					'enabled' => '1',
					'name' => 'canMove',
					'title' => 'Can Move Threads',
					'desc' => 'Set whether members of this group can move threads in forums they moderate',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'12' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => '',
					'subcat' => 'gprofile',
					'enabled' => '1',
					'name' => 'displayRank',
					'title' => 'Display Rank on posts',
					'desc' => 'Choose whether to display the rank (yes) or the group name (no) next to users posts',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'13' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'modopts',
					'subcat' => 'mod',
					'enabled' => '1',
					'name' => 'canDeletePosts',
					'title' => 'Can Delete Posts',
					'desc' => 'Set whether members of this group can delete posts in forums they moderate',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'14' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'ownopts',
					'subcat' => 'own',
					'enabled' => '1',
					'name' => 'canDeleteOwnPosts',
					'title' => 'Can Delete Own Posts',
					'desc' => 'Set whether members of this group can delete their own posts',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'15' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'modopts',
					'subcat' => 'mod',
					'enabled' => '1',
					'name' => 'canEditPosts',
					'title' => 'Can Edit Posts',
					'desc' => 'Set whether members of this group can edit posts in forums they moderate',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'16' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'ownopts',
					'subcat' => 'own',
					'enabled' => '1',
					'name' => 'canEditOwnPosts',
					'title' => 'Can Edit Own Posts',
					'desc' => 'Set whether members of this group can edit their own posts',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'17' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'ownopts',
					'subcat' => 'own',
					'enabled' => '1',
					'name' => 'canRep',
					'title' => 'Can Report Posts',
					'desc' => 'Set whether members of this group can report posts',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '1',
				),
				'18' => array(
					'modId' => 'net.cipherpixel.forum',
					'order' => '0',
					'tab' => 'modopts',
					'subcat' => 'mod',
					'enabled' => '1',
					'name' => 'canRename',
					'title' => 'Can Rename Threads',
					'desc' => 'Set whether members of this group can rename threads in forums they moderate',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
			),
	
			'modules' => array(
				'0' => array(
					'unique_id' => 'net.cipherpixel.forum',
					'status' => '1',
					'name' => 'forum',
					'sexyname' => 'CP-Forum',
					'ver' => '1.0.0.b',
					'acp_field' => 'acp',
					'defSkin' => 'forum2',
				),
			),
	
			'tools' => array(
				'0' => array(
					'enabled' => '1',
					'modId' => 'net.cipherpixel.forum',
					'name' => 'Fix last poster',
					'desc' => 'Updates last post user and last post time for every forum',
					'task' => 'lastPosts',
					'res' => '2',
				),
				'1' => array(
					'enabled' => '1',
					'modId' => 'net.cipherpixel.forum',
					'name' => 'Fix Forum permission rows',
					'desc' => 'Ensures each forum row has a matching permission row',
					'task' => 'forumToPerm',
					'res' => '1',
				),
				'2' => array(
					'enabled' => '1',
					'modId' => 'net.cipherpixel.forum',
					'name' => 'Count Posts',
					'desc' => 'Counts Posts',
					'task' => 'countPosts',
					'res' => '3',
				),
			),
	
		);

		
	}
	
	public function first_data()
	{
		
		return array(
			'forums' => array(
				'0' => array(
					'name' => 'Example Category',
					'slug' => 'example-category',
					'order' => '1',
				),
				'1' => array(
					'name' => 'Your first forum',
					'desc' => 'This is an example forum',
					'slug' => 'your-first-forum',
					'parent' => '1',
					'allowThreads' => '1',
					'lastPostTime' => 'CP_INS_TIME',
					'lastPostUser' => '1',
					'lastPostThread' => '1',
					'postCount' => '1',
					'threadCount' => '1',
					'isLink' => '0',
					'newTab' => '0',
					'linkUrl' => '',
					'threadSortField' => 'lastPostTime',
					'threadSortOrder' => 'desc',
					'order' => '1',
				),
			),
	
			'perm_reg' => array(
				'0' => array(
					'type' => 'forum',
					'type_id' => '2',
					'p_read' => ',1,2,3,4,',
					'p_start' => ',1,2,',
					'p_post' => ',1,2,',
					'p_upload' => ',1,2,',
					'p_download' => ',1,2,',
				),
			),
	
			'threads' => array(
				'0' => array(
					'title' => 'The thread to start all threads',
					'slug' => 'the-thread-to-start-all-threads',
					'forumId' => '2',
					'firstPost' => '1',
					'starterId' => '1',
					'startTime' => 'CP_INS_TIME',
					'lastPostTime' => 'CP_INS_TIME',
					'lastPost' => '1',
					'lastPostUser' => '1',
					'postCount' => '1',
					'visible' => '1',
				),
			),
	
			'posts' => array(
				'0' => array(
					'visible' => '1',
					'posterId' => '1',
					'threadId' => '1',
					'postTime' => 'CP_INS_TIME',
					'postContent' => 'Hello and welcome to your CP-Forum.

This is a post, it is located in a thread, which is located in a forum.

Please visit&nbsp;[url=http://cipherpixel.net]cipherpixel[/url]\\\\\\\'s forums for further help and support, or if you wish to place feedback about CP-Forum.

Enjoy your day!',
				),
			),
	
			'miscstat' => array(
				'0' => array(
					'arrayTitle' => 'totalThreads',
					'value' => '1',
				),
				'1' => array(
					'arrayTitle' => 'totalPosts',
					'value' => '1',
				),
			),
	
			'skins' => array(
				'0' => array(
					'id' => 'forum2',
					'sexyname' => 'Forum 2.0',
					'dev' => 'CipherPixel',
					'devlink' => 'http://cipherpixel.net',
					'public' => '1',
					'p_apps' => ',forum,',
				),
			),
	
		);

		
	}
	
}

?>