<?php
	
class app_install_admin {
	
	/**
	** This file has been automatically generated
	** TS: 1417437248 (1st of December 2014 01:34:08 PM)
	** 
	** Do not edit. Use CP Build Tools
	*/
	
	public function info()
	{
		return array(
			'unique_id'	=> 'com.notionbb.admin',
			'name' 		=> 'admin',
			'sexyname' 	=> 'CP-Core',
			'desc' 		=> '',
			'ver'  		=> '1.1A',
		);
	}
	
	public function structure_queries()
	{
		
		return '{"admin_logs":{"time":{"Field":"time","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":""},"table":{"Field":"table","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"row":{"Field":"row","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"before":{"Field":"before","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"after":{"Field":"after","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"by":{"Field":"by","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""}},"cache":{"key":{"Field":"key","Type":"varchar(50)","Null":"NO","Key":"PRI","Default":null,"Extra":""},"value":{"Field":"value","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"last_update":{"Field":"last_update","Type":"varchar(20)","Null":"NO","Key":"","Default":null,"Extra":""}},"globalcats":{"text_id":{"Field":"text_id","Type":"varchar(50)","Null":"NO","Key":"PRI","Default":null,"Extra":""},"order":{"Field":"order","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"enabled":{"Field":"enabled","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},"modId":{"Field":"modId","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"subcat":{"Field":"subcat","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"name":{"Field":"name","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"desc":{"Field":"desc","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"icon":{"Field":"icon","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}},"globals":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"catId":{"Field":"catId","Type":"varchar(50)","Null":"NO","Key":"","Default":null,"Extra":""},"tab":{"Field":"tab","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"subcat":{"Field":"subcat","Type":"varchar(50)","Null":"NO","Key":"","Default":null,"Extra":""},"modId":{"Field":"modId","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"arrayTitle":{"Field":"arrayTitle","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"title":{"Field":"title","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"desc":{"Field":"desc","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"value":{"Field":"value","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"valueType":{"Field":"valueType","Type":"varchar(20)","Null":"NO","Key":"","Default":"field","Extra":""},"valueFunction":{"Field":"valueFunction","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"valueOptions":{"Field":"valueOptions","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"valueDef":{"Field":"valueDef","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}},"groups":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"enabled":{"Field":"enabled","Type":"int(1)","Null":"NO","Key":"","Default":"1","Extra":""},"name":{"Field":"name","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"permSet":{"Field":"permSet","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"userCount":{"Field":"userCount","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"htmlPrefix":{"Field":"htmlPrefix","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"htmlSuffix":{"Field":"htmlSuffix","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"acp":{"Field":"acp","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"canViewMembers":{"Field":"canViewMembers","Type":"int(1)","Null":"NO","Key":"","Default":"1","Extra":""},"displayRank":{"Field":"displayRank","Type":"int(1)","Null":"NO","Key":"","Default":"1","Extra":""}},"groupsettings":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"modId":{"Field":"modId","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"order":{"Field":"order","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"tab":{"Field":"tab","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"subcat":{"Field":"subcat","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"enabled":{"Field":"enabled","Type":"int(1)","Null":"NO","Key":"","Default":"1","Extra":""},"name":{"Field":"name","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"title":{"Field":"title","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"desc":{"Field":"desc","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"valueType":{"Field":"valueType","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"valueFunction":{"Field":"valueFunction","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"valueDef":{"Field":"valueDef","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}},"miscstat":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"arrayTitle":{"Field":"arrayTitle","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"value":{"Field":"value","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""}},"modules":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"unique_id":{"Field":"unique_id","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"status":{"Field":"status","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"name":{"Field":"name","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"sexyname":{"Field":"sexyname","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"ver":{"Field":"ver","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"acp_field":{"Field":"acp_field","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"defSkin":{"Field":"defSkin","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""}},"notifications":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"user_id":{"Field":"user_id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":""},"from":{"Field":"from","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"read":{"Field":"read","Type":"int(1)","Null":"NO","Key":"","Default":"0","Extra":""},"type":{"Field":"type","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"time":{"Field":"time","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"thread_id":{"Field":"thread_id","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"post_id":{"Field":"post_id","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"repetitive":{"Field":"repetitive","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""}},"online":{"id":{"Field":"id","Type":"varchar(25)","Null":"NO","Key":"PRI","Default":null,"Extra":""},"userId":{"Field":"userId","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"lastClick":{"Field":"lastClick","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""}},"perm":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"name":{"Field":"name","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}},"perm_reg":{"pid":{"Field":"pid","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"type":{"Field":"type","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"type_id":{"Field":"type_id","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"p_read":{"Field":"p_read","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"p_start":{"Field":"p_start","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"p_g_start":{"Field":"p_g_start","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"p_u_start":{"Field":"p_u_start","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"p_post":{"Field":"p_post","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"p_upload":{"Field":"p_upload","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"p_download":{"Field":"p_download","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"p_edit":{"Field":"p_edit","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}},"ranks":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"title":{"Field":"title","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"minPosts":{"Field":"minPosts","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"pip":{"Field":"pip","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}},"reports":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"status":{"Field":"status","Type":"int(11)","Null":"NO","Key":"","Default":"0","Extra":""},"type":{"Field":"type","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"relId":{"Field":"relId","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"sendTime":{"Field":"sendTime","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"from":{"Field":"from","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"msg":{"Field":"msg","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}},"rowbin":{"id":{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"fromTable":{"Field":"fromTable","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"deleteDate":{"Field":"deleteDate","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"oldId":{"Field":"oldId","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"array":{"Field":"array","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}},"skins":{"id":{"Field":"id","Type":"varchar(225)","Null":"NO","Key":"PRI","Default":null,"Extra":""},"sexyname":{"Field":"sexyname","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"dev":{"Field":"dev","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"devlink":{"Field":"devlink","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"public":{"Field":"public","Type":"int(1)","Null":"NO","Key":"","Default":"1","Extra":""},"p_apps":{"Field":"p_apps","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"p_read":{"Field":"p_read","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"p_g_read":{"Field":"p_g_read","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"p_u_read":{"Field":"p_u_read","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}},"tools":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"enabled":{"Field":"enabled","Type":"int(1)","Null":"NO","Key":"","Default":"1","Extra":""},"modId":{"Field":"modId","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"name":{"Field":"name","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"desc":{"Field":"desc","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"task":{"Field":"task","Type":"varchar(20)","Null":"NO","Key":"UNI","Default":null,"Extra":""},"res":{"Field":"res","Type":"int(2)","Null":"NO","Key":"","Default":"1","Extra":""}},"users":{"id":{"Field":"id","Type":"int(255)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"email":{"Field":"email","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"cookieId":{"Field":"cookieId","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"validated":{"Field":"validated","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"validateCode":{"Field":"validateCode","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"displayName":{"Field":"displayName","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"realName":{"Field":"realName","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"ow_displayName":{"Field":"ow_displayName","Type":"int(1)","Null":"NO","Key":"","Default":"0","Extra":""},"groupId":{"Field":"groupId","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"cur_ban":{"Field":"cur_ban","Type":"int(1)","Null":"NO","Key":"","Default":"0","Extra":""},"userPermSet":{"Field":"userPermSet","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"unreadNoti":{"Field":"unreadNoti","Type":"int(1)","Null":"NO","Key":"","Default":"0","Extra":""},"notiArray":{"Field":"notiArray","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"regDate":{"Field":"regDate","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"modPops":{"Field":"modPops","Type":"int(1)","Null":"NO","Key":"","Default":"1","Extra":""},"awardsArray":{"Field":"awardsArray","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"avatar":{"Field":"avatar","Type":"varchar(225)","Null":"NO","Key":"","Default":"images\/noav.jpg","Extra":""},"quote":{"Field":"quote","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"djName":{"Field":"djName","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"profileViews":{"Field":"profileViews","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"location":{"Field":"location","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"email_show":{"Field":"email_show","Type":"int(1)","Null":"NO","Key":"","Default":null,"Extra":""},"occupation":{"Field":"occupation","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"twitter":{"Field":"twitter","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"google":{"Field":"google","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"facebook":{"Field":"facebook","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"youtube":{"Field":"youtube","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"website":{"Field":"website","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"signature":{"Field":"signature","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}},"users_bans":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"user_id":{"Field":"user_id","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"mod_id":{"Field":"mod_id","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"type":{"Field":"type","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"time_start":{"Field":"time_start","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"time_end":{"Field":"time_end","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""}},"users_secure":{"id":{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"pass":{"Field":"pass","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"string":{"Field":"string","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"google_id":{"Field":"google_id","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"facebook_id":{"Field":"facebook_id","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}},"usersettings":{"id":{"Field":"id","Type":"int(225)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},"modId":{"Field":"modId","Type":"varchar(225)","Null":"NO","Key":"","Default":null,"Extra":""},"order":{"Field":"order","Type":"int(225)","Null":"NO","Key":"","Default":null,"Extra":""},"subcat":{"Field":"subcat","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"enabled":{"Field":"enabled","Type":"varchar(1)","Null":"NO","Key":"","Default":"1","Extra":""},"name":{"Field":"name","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"title":{"Field":"title","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"desc":{"Field":"desc","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"valueType":{"Field":"valueType","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"valueFunction":{"Field":"valueFunction","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""},"valueDef":{"Field":"valueDef","Type":"text","Null":"NO","Key":"","Default":null,"Extra":""}}}';

		
	}
	
	public function init_queries()
	{
		
		return array(
			'globalcats' => array(
				'0' => array(
					'text_id' => 'developers_and_debug',
					'order' => '7',
					'enabled' => '1',
					'modId' => 'com.notionbb.admin',
					'subcat' => 'asystem',
					'name' => 'Developers and Debug',
					'desc' => 'Settings to help in development',
					'icon' => 'images/globalicons/wrench.png',
				),
				'1' => array(
					'text_id' => 'facebook_api',
					'order' => '3',
					'enabled' => '1',
					'modId' => 'com.notionbb.admin',
					'subcat' => 'busers',
					'name' => 'Facebook API',
					'desc' => 'Manage Facebook Login and API Options',
					'icon' => 'images/globalicons/def.png',
				),
				'2' => array(
					'text_id' => 'file_uploads',
					'order' => '6',
					'enabled' => '1',
					'modId' => 'com.notionbb.admin',
					'subcat' => 'asystem',
					'name' => 'File Uploads',
					'desc' => 'Change file upload options',
					'icon' => 'images/globalicons/attach.png',
				),
				'3' => array(
					'text_id' => 'seo_and_analytics',
					'order' => '2',
					'enabled' => '1',
					'modId' => 'com.notionbb.admin',
					'subcat' => 'asystem',
					'name' => 'SEO and Analytics',
					'desc' => 'Settings related to Search Engine Optimisation and Analytics',
					'icon' => 'images/globalicons/find.png',
				),
				'4' => array(
					'text_id' => 'site_settings',
					'order' => '1',
					'enabled' => '1',
					'modId' => 'com.notionbb.admin',
					'subcat' => 'asystem',
					'name' => 'Site Settings',
					'desc' => 'Global site settings',
					'icon' => 'images/globalicons/site.png',
				),
				'5' => array(
					'text_id' => 'spam_and_security',
					'order' => '4',
					'enabled' => '1',
					'modId' => 'com.notionbb.admin',
					'subcat' => 'asystem',
					'name' => 'Spam and Security',
					'desc' => 'Settings that fight against spam and server attacks',
					'icon' => 'images/globalicons/secure.png',
				),
				'6' => array(
					'text_id' => 'users_and_groups',
					'order' => '1',
					'enabled' => '1',
					'modId' => 'com.notionbb.admin',
					'subcat' => 'busers',
					'name' => 'Users and Groups',
					'desc' => 'User and Group Settings',
					'icon' => 'images/globalicons/users.png',
				),
			),
	
			'globals' => array(
				'0' => array(
					'catId' => 'site_settings',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'siteName',
					'title' => 'Site Name',
					'desc' => 'Appears in browser header and other locations around the site',
					'value' => 'Your CP-Forum',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'1' => array(
					'catId' => 'users_and_groups',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'unloggedGroup',
					'title' => 'Guest User Group',
					'desc' => 'Group where users who are not logged in are placed',
					'value' => '4',
					'valueType' => 'drop',
					'valueFunction' => 'getGroups',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'2' => array(
					'catId' => 'spam_and_security',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'maxLoginAttempts',
					'title' => 'Maximum Login Attempts',
					'desc' => 'Maximum Login Attempts allowed per \\\"maxLoginTime\\\"',
					'value' => '3',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'3' => array(
					'catId' => 'spam_and_security',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'maxLoginTime',
					'title' => 'Maximum Login Time',
					'desc' => 'How long to wait if MaxLoginAttempts is violated',
					'value' => '30',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'4' => array(
					'catId' => 'spam_and_security',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'maxPostTime',
					'title' => 'Post Time',
					'desc' => 'Time a user has to wait before they can post again',
					'value' => '30',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'5' => array(
					'catId' => 'spam_and_security',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'loggedToSearchMem',
					'title' => 'Logged in search members',
					'desc' => 'Do users need to be logged in to search for members?',
					'value' => '1',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'6' => array(
					'catId' => 'site_settings',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'splashTime',
					'title' => 'Splash Time',
					'desc' => 'Set (in seconds) how long splash pages are shown for',
					'value' => '1',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'7' => array(
					'catId' => 'site_settings',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'jQueryUrl',
					'title' => 'jQuery Url',
					'desc' => 'Enter the URl to the remote jQuery file',
					'value' => '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'8' => array(
					'catId' => 'spam_and_security',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'ReCaptchaStatus',
					'title' => 'Use ReCaptcha',
					'desc' => 'Set whether to use enable ReCapture or not ',
					'value' => '1',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '1',
				),
				'9' => array(
					'catId' => 'spam_and_security',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'recapPubKey',
					'title' => 'ReCaptcha Public Key',
					'desc' => 'Use our ReCaptcha public key, or get you own at ReCaptcha ',
					'value' => '6Le_W-8SAAAAAHTHuv6VsLMMpj7LPfvKPkYID7_i',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'10' => array(
					'catId' => 'spam_and_security',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'recapPriKey',
					'title' => 'ReCaptcha Private Key',
					'desc' => 'Use our ReCaptcha private key, or get you own at ReCaptcha ',
					'value' => '6Le_W-8SAAAAANRXuMC5zVjNuWZUl59jTKqY0-Xm',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'11' => array(
					'catId' => 'users_and_groups',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'newmemGroup',
					'title' => 'New Member Group',
					'desc' => 'Set which group newly registered users should go into',
					'value' => '2',
					'valueType' => 'drop',
					'valueFunction' => 'getGroups',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'12' => array(
					'catId' => 'users_and_groups',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'validateMembers',
					'title' => 'Validate Members',
					'desc' => 'Set whether members need to validate their emails before being moved into default member group',
					'value' => '0',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'13' => array(
					'catId' => 'users_and_groups',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'validatingGroup',
					'title' => 'Validating Group',
					'desc' => 'Set which group unvalidated members should go into',
					'value' => '3',
					'valueType' => 'drop',
					'valueFunction' => 'getGroups',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'14' => array(
					'catId' => 'seo_and_analytics',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'seoDesc',
					'title' => 'Website Description',
					'desc' => 'The meta description tag is meant to be a short and accurate summary of your page content. This 
description can affect your search engine rankings and can also show up directly in search engine 
results (and affect whether or not the user clicks through to your site).
',
					'value' => '',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'15' => array(
					'catId' => 'seo_and_analytics',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'seoKeywords',
					'title' => 'SEO Keywords',
					'desc' => 'The meta keywords tag allows you to provide additional text for search engines to index along with 
the rest of what youve written on your page. Meta keywords can emphasize a particular word or 
phrase in the main body of your text.',
					'value' => '',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'16' => array(
					'catId' => 'seo_and_analytics',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'favicon',
					'title' => 'Favicon URL',
					'desc' => 'Enter the URL to your favicon image',
					'value' => 'images/favicon.ico',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'17' => array(
					'catId' => 'seo_and_analytics',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'g_analytics',
					'title' => 'Google Analytics Code',
					'desc' => 'Enter your Google Analyics code tracking code.&amp;lt;script&amp;gt; tags not required',
					'value' => '',
					'valueType' => 'area_entity',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'18' => array(
					'catId' => 'site_settings',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'jQueryUIUrl',
					'title' => 'jQuery UI Url',
					'desc' => 'Enter the URL to the jQuery UI library',
					'value' => '//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'19' => array(
					'catId' => 'users_and_groups',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'pipImg',
					'title' => 'Pip Image',
					'desc' => 'Enter the file name for the pip image you would like to use',
					'value' => 'star2.gif',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'20' => array(
					'catId' => 'users_and_groups',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'forceLogin',
					'title' => 'Login each visit',
					'desc' => 'Set whether users must login each visit (yes) or allow login automatically if users set to \\\"remember me\\\" ',
					'value' => '0',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueOptions' => 'Array',
					'valueDef' => '',
				),
				'21' => array(
					'catId' => 'site_settings',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'shortdate',
					'title' => 'Short Date Format',
					'desc' => '',
					'value' => 'd/m/y',
					'valueType' => 'drop',
					'valueFunction' => '',
					'valueOptions' => 'a:6:{s:18:\\\"Day / Month / Year\\\";s:5:\\\"d/m/y\\\";s:18:\\\"Month / Day / Year\\\";s:5:\\\"m/d/y\\\";s:18:\\\"Year / Month / Day\\\";s:5:\\\"y/m/d\\\";s:14:\\\"Day.Month.Year\\\";s:5:\\\"d.m.y\\\";s:14:\\\"Month.Day.Year\\\";s:5:\\\"m.d.y\\\";s:14:\\\"Year.Month.Day\\\";s:5:\\\"y.m.d\\\";}',
					'valueDef' => '',
				),
				'22' => array(
					'catId' => 'file_uploads',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'userUploadDir',
					'title' => 'User Upload Directory',
					'desc' => 'Enter the where user uploaded files should go. Does not need a slash at start or end.&amp;lt;br /&amp;gt;E.g. \\\"images/uploads\\\"',
					'value' => 'uploads',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'23' => array(
					'catId' => 'file_uploads',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'allowedFileType',
					'title' => 'Allowed File Type',
					'desc' => 'Enter the files types that users are allowed to upload. Separate with comma, no spaces.&lt;br /&gt;
&lt;a href=\\\"https://en.wikipedia.org/wiki/Internet_media_type#List_of_common_media_types\\\"&gt;MIME File Types&lt;/a&gt;',
					'value' => 'image/png,image/gif,image/jpeg',
					'valueType' => 'area',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'24' => array(
					'catId' => 'users_and_groups',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'forceDisplay',
					'title' => 'Force Display Name',
					'desc' => 'If set to yes (recommended), a user who creates an account via oauth (eg, Google, Facebook etc) will be required to set a display name.',
					'value' => '1',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'25' => array(
					'catId' => 'google_api',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'googleLogin',
					'title' => 'Allow Google Login',
					'desc' => 'Set whether to allow users to login from Google.&lt;br /&gt; You will need to setup a Google Project and allow the \\\"Google+ API\\\"',
					'value' => '0',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '0',
				),
				'26' => array(
					'catId' => 'google_api',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'googleId',
					'title' => 'Client ID',
					'desc' => 'Enter your Google client ID. Create one by starting a project at https://console.developers.google.com',
					'value' => '',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => 'EMPTY',
				),
				'27' => array(
					'catId' => 'google_api',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'googleSecret',
					'title' => 'Client Secret',
					'desc' => 'Enter the project\\\'s Client Secret code',
					'value' => '',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => 'EMPTY',
				),
				'28' => array(
					'catId' => 'google_api',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'googleURI',
					'title' => 'Redirect URI',
					'desc' => 'Enter the URL to google callback page. Make sure this is also entered into your google project settings. For example:&lt;br /&gt;
http://example.com/index.php/forum/login/google or&lt;br /&gt;
http://example.com/?app=forum&amp;1=login&amp;2=google',
					'value' => 'http://yourwebsite/index.php/forum/login/google',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => 'http://yourwebsite/index.php/forum/login/google',
				),
				'29' => array(
					'catId' => 'developers_and_debug',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'dev_mode',
					'title' => 'Developer Mode',
					'desc' => 'Enables admin panel developer features',
					'value' => '0',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '0',
				),
				'30' => array(
					'catId' => 'developers_and_debug',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'ow_DEBUG',
					'title' => 'Debug',
					'desc' => 'Whether to display debug information at the bottom of every page.&amp;lt;br /&amp;gt;If set to yes, will overwrite the init.php DEBUG setting.',
					'value' => '0',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '0',
				),
				'31' => array(
					'catId' => 'users_and_groups',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'defAvatar',
					'title' => 'Default Avatar',
					'desc' => 'Enter the default avatar new users will be given. ',
					'value' => 'images/noav.jpg',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '',
				),
				'32' => array(
					'catId' => 'facebook_api',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'facebook_allow',
					'title' => 'Allow Facebook Login',
					'desc' => 'Set whether to allow users to login from Facebook.
You will need to setup a Facebook App. Your website URL will need to be set as a redirect URI. Requires PHP 5.4 or greater',
					'value' => '0',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => '0',
				),
				'33' => array(
					'catId' => 'facebook_api',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'facebook_app_id',
					'title' => 'App Id',
					'desc' => 'Obtained from the Facebook Developers dashboard',
					'value' => '',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => 'EMPTY',
				),
				'34' => array(
					'catId' => 'facebook_api',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'facebook_secret',
					'title' => 'App Secret',
					'desc' => 'Enter App Secret',
					'value' => '',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => 'EMPTY',
				),
				'35' => array(
					'catId' => 'facebook_api',
					'tab' => '',
					'subcat' => '',
					'modId' => 'com.notionbb.admin',
					'arrayTitle' => 'facebook_uri',
					'title' => 'Redirect URI',
					'desc' => 'Enter the URL to facebook callback page. Make sure this is also entered into your facebook app settings. For example:&lt;br /&gt;
http://example.com/index.php/forum/login/facebook',
					'value' => 'http://yourwebsite/index.php/forum/login/facebook',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueOptions' => '',
					'valueDef' => 'http://yourwebsite/index.php/forum/login/facebook',
				),
			),
	
			'groupsettings' => array(
				'0' => array(
					'modId' => 'com.notionbb.admin',
					'order' => '0',
					'tab' => '',
					'subcat' => 'gprofile',
					'enabled' => '1',
					'name' => 'name',
					'title' => 'Group name',
					'desc' => 'Change what you want this group to be called',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueDef' => '',
				),
				'1' => array(
					'modId' => 'com.notionbb.admin',
					'order' => '0',
					'tab' => '',
					'subcat' => 'gprofile',
					'enabled' => '1',
					'name' => 'htmlPrefix',
					'title' => 'Html Prefix',
					'desc' => 'Html to be output before showing this groups name',
					'valueType' => 'field_entity',
					'valueFunction' => '',
					'valueDef' => '&lt;span style=\\\"\\\"&gt;',
				),
				'2' => array(
					'modId' => 'com.notionbb.admin',
					'order' => '0',
					'tab' => '',
					'subcat' => 'gprofile',
					'enabled' => '1',
					'name' => 'htmlSuffix',
					'title' => 'Html Suffix',
					'desc' => 'Html to be output after showing this groups name',
					'valueType' => 'field_entity',
					'valueFunction' => '',
					'valueDef' => '&lt;/span&gt;',
				),
				'3' => array(
					'modId' => 'com.notionbb.admin',
					'order' => '0',
					'tab' => '',
					'subcat' => 'access',
					'enabled' => '1',
					'name' => 'acp',
					'title' => 'ACP Access',
					'desc' => 'Select whether this group can access the Admin control panel',
					'valueType' => 'onoff',
					'valueFunction' => '',
					'valueDef' => '0',
				),
				'4' => array(
					'modId' => 'com.notionbb.admin',
					'order' => '0',
					'tab' => '',
					'subcat' => 'access',
					'enabled' => '1',
					'name' => 'permSet',
					'title' => 'Permission Set',
					'desc' => 'Select which permission set this group will use',
					'valueType' => 'drop',
					'valueFunction' => 'getPerms',
					'valueDef' => '',
				),
			),
	
			'modules' => array(
				'0' => array(
					'unique_id' => 'com.notionbb.admin',
					'status' => '1',
					'name' => 'admin',
					'sexyname' => 'CP-Core',
					'ver' => '1.0.0.b',
					'acp_field' => 'acp',
					'defSkin' => 'admin3',
				),
			),
	
			'usersettings' => array(
				'0' => array(
					'modId' => 'com.notionbb.admin',
					'order' => '0',
					'subcat' => 'access',
					'enabled' => '1',
					'name' => 'email',
					'title' => 'Email Address',
					'desc' => 'Users email address used to login',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueDef' => '',
				),
				'1' => array(
					'modId' => 'com.notionbb.admin',
					'order' => '1',
					'subcat' => 'basic',
					'enabled' => '1',
					'name' => 'displayName',
					'title' => 'Display Name',
					'desc' => 'Enter this users display name',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueDef' => '',
				),
				'2' => array(
					'modId' => 'com.notionbb.admin',
					'order' => '0',
					'subcat' => 'basic',
					'enabled' => '1',
					'name' => 'groupId',
					'title' => 'Group',
					'desc' => 'Select what group this user is in',
					'valueType' => 'drop',
					'valueFunction' => 'getGroups',
					'valueDef' => '2',
				),
				'3' => array(
					'modId' => 'com.notionbb.admin',
					'order' => '0',
					'subcat' => 'basic',
					'enabled' => '1',
					'name' => 'avatar',
					'title' => 'Avatar',
					'desc' => 'Enter an image URL for your avatar',
					'valueType' => 'field',
					'valueFunction' => '',
					'valueDef' => 'images/noav.jpg',
				),
				'4' => array(
					'modId' => 'com.notionbb.admin',
					'order' => '0',
					'subcat' => 'access',
					'enabled' => '1',
					'name' => 'pass_ignore',
					'title' => 'Password',
					'desc' => 'Enter a password for this user. Leave blank to keep the same.',
					'valueType' => 'blankfield',
					'valueFunction' => '',
					'valueDef' => '',
				),
				'5' => array(
					'modId' => 'com.notionbb.admin',
					'order' => '0',
					'subcat' => 'perm',
					'enabled' => '1',
					'name' => 'userPermSet',
					'title' => 'Permission Set',
					'desc' => 'Select whether you wish to override a groups permission set with the one below',
					'valueType' => 'drop',
					'valueFunction' => 'getPerms',
					'valueDef' => '0',
				),
			),
	
			'tools' => array(
				'0' => array(
					'enabled' => '1',
					'modId' => 'com.notionbb.admin',
					'name' => 'Recache Global Variables',
					'desc' => 'Recache Global Variables',
					'task' => 'cacheGlobals',
					'res' => '1',
				),
				'1' => array(
					'enabled' => '1',
					'modId' => 'com.notionbb.admin',
					'name' => 'Recache Menu Bar',
					'desc' => 'Recache Menu Bar',
					'task' => 'cacheMenubar',
					'res' => '1',
				),
				'2' => array(
					'enabled' => '1',
					'modId' => 'com.notionbb.admin',
					'name' => 'Count Members in Groups',
					'desc' => 'Counts members in each group',
					'task' => 'countMemberGroups',
					'res' => '2',
				),
			),
	
		);

		
	}
	
	public function first_data()
	{
		
		return array(
			'groups' => array(
				'0' => array(
					'enabled' => '1',
					'name' => 'Root Admin',
					'permSet' => '1',
					'userCount' => '0',
					'htmlPrefix' => '<span style=\"color: darkblue\">',
					'htmlSuffix' => '</span>',
					'acp' => '1',
				),
				'1' => array(
					'enabled' => '1',
					'name' => 'Member',
					'permSet' => '2',
					'userCount' => '0',
					'htmlPrefix' => '<span>',
					'htmlSuffix' => '</span>',
					'acp' => '0',
				),
				'2' => array(
					'enabled' => '1',
					'name' => 'Validating',
					'permSet' => '3',
					'userCount' => '0',
					'htmlPrefix' => '<span style=\"font-style: italic;\">',
					'htmlSuffix' => '</span>',
					'acp' => '0',
				),
				'3' => array(
					'enabled' => '1',
					'name' => 'Guest',
					'permSet' => '3',
					'userCount' => '0',
					'htmlPrefix' => '<span style=\"color: grey;\">',
					'htmlSuffix' => '</span>',
					'acp' => '0',
				),
				'4' => array(
					'enabled' => '1',
					'name' => 'Moderator',
					'permSet' => '1',
					'userCount' => '0',
					'htmlPrefix' => '<span style=\"color: green\">',
					'htmlSuffix' => '</span>',
					'acp' => '0',
				),
				'5' => array(
					'enabled' => '1',
					'name' => 'Banned',
					'permSet' => '4',
					'userCount' => '0',
					'htmlPrefix' => '<del style=\"color: grey;\">',
					'htmlSuffix' => '</del>',
					'acp' => '0',
				),
			),
	
			'perm' => array(
				'0' => array(
					'id' => '1',
					'name' => 'Staff',
				),
				'1' => array(
					'id' => '2',
					'name' => 'Members',
				),
				'2' => array(
					'id' => '3',
					'name' => 'Guests',
				),
				'3' => array(
					'id' => '4',
					'name' => 'Banned',
				),
			),
	
			'miscstat' => array(
				'0' => array(
					'arrayTitle' => 'totalUsers',
					'value' => '0',
				),
				'1' => array(
					'arrayTitle' => 'latestUser',
					'value' => '0',
				),
			),
	
			'skins' => array(
				'0' => array(
					'id' => 'admin3',
					'sexyname' => 'Admin 3.0',
					'dev' => 'NotionBB',
					'devlink' => 'http://notionbb.com',
					'public' => '1',
					'p_apps' => ',admin,',
				),
			),
	
		);

		
	}
	
}

?>
